Revert "perf: duplicate deletion of perf event"
This reverts commit a41ef8425798c959f737f30e5aedb0a96d108634.

lineage-16.0: fixes below error:
kernel/samsung/universal5433/kernel/events/core.c:6748:10:
error: 'struct perf_event_attr' has no member named 'constraint_duplicate'

Change-Id: I097e69e51736995f7510fedb7e43e750fa7c83b6